INSERT INTO CHAPTER
(CHAP_DESCR, CHAP_TITLE, ORDER_ID)
VALUES('This is the first chapter','First Chapter',1);

INSERT INTO CHAPTER_PAGE
(CHAP_ID, PAGE_NUM, PAGE_URL)
VALUES(0,1,'HTTP://PAGE.URL.COM');

INSERT INTO CHAPTER
(CHAP_ID, SUB_CHAP_DESCR, SUB_CHAP_TITLE, ORDER_ID)
VALUES(0,'This is the first sub chapter','First Sub Chapter',1);

INSERT INTO MULTI_CHOICE_Q
(Q_TXT,HELP_TXT,CORR_ANS,SUB_CHAP_ID,ORDER_ID)
VALUES('What is your favorite color?','Hint: Blue', 1, 0, 1);

INSERT INTO MULTI_CHOICE_OPTION
(MC_Q_ID, CHOICE_TXT)
VALUES(0,"Blue")

INSERT INTO MC_USER_ANS
VALUES(0,0,1);

INSERT INTO SHORT_ANS_Q
(SUB_CHAP_ID,QUESTION,HELP_TXT,ORDER_ID)
VALUES(0,'Write about your favorite color.','Hint: Write about blue.',1);

INSERT INTO SHORT_ANS_USER_ANS
(0,0,'My favority color is blue.',0,1);

INSERT INTO UPLOAD_FILE_Q
(SUB_CHAP_ID,QUESTION,HELP_TXT,ORDER_ID)
VALUES(0,'Write an essay about your favorite color.','Hint: Write about blue.');

INSERT INTO UPLOADED_ANS
(UP_Q_ID, MEDIA_TYP_ID, FILE_PATH, USR_ID, APRVD, SHARED)
VALUES(0,1,'HTTPS://FILE.PATH.SQL',0,1,1);

INSERT INTO COMMENT_FLAG
(FLGD_BY, CMNT_ID)
VALUES(0,0);

INSERT INTO COMMENT_LIKE
(LKD_BY,CMNT_ID)
VALUES(0,0);

INSERT INTO UPLOAD_ANS_FLAG
(FLGD_BY, UP_ANS_ID)
VALUES(0,0);

INSERT INTO UPLOAD_ANS_LIKE
(LKD_BY,UP_ANS_ID)
VALUES(0,0);

INSERT INTO UPLOAD_POST_FLAG
(FLGD_BY, POST_ID)
VALUES(0,0);

INSERT INTO UPLOAD_POST_LIKE
(LKD_BY,POST_ID)
VALUES(0,0);

INSERT INTO INSTRUCTOR
(USR_ID,N_STDNT,TOT_CAP,START_DT)
VALUES(0,1,5,CURRENT_DATE);

INSERT INTO STUDENT
(USR_ID,ROSTER_ID,CRNT_SUB_CHAP_ID,START_DT)
VALUES(0,0,0,CURRENT_DATE);

INSERT INTO USERS
(EMAIL,USR_NM,PWD,ROLE_TYP_CD,RGSTRD,INVIT_CD,INVIT_BY,INVIT_DT,USR_STS_ID,FRST_NM,LST_NM,CITY,STATE,ABT_ME)
VALUES('ASHWINISKEWL@GMAIL.COM','ASHWINJ','BLUE','S',1,'LA1234LKJ32','TOM FUENTES',CURRENT_DATE,0,'ASHWIN','JACOB','CHICAGO','IL','I AM FRONT-END DEVELOPER');

INSERT INTO USER_STATUS
(USR_ID,STS_TYP_CD,STRT_DT,END_DT)
VALUES(0,'S',CURRENT_DATE, CURRENT_DATE + 7);

INSERT INTO SUPER_ADMIN
(0);

INSERT INTO UPLOAD_POST
(SUBJ_TXT,DESCR_TXT,FILE_PATH,MEDIA_TYP_ID,USR_ID)
VALUES('Favorite color','My favorite color is blue','HTTP://UPLOAD.POST.COM',0);